### ISSUE TITLE
Enhancement: display text as json structure.

### ISSUE THREAD

**Issue by Yomodo** [lzinga/BlazorTextDiff#4]
It would be awesome to be able to display json-text as a json structure.

**Comment by MariaCobretti** [comment]
upvote

**Comment by Yomodo** [comment]
Closing this one; to get a properly indented JSON string, one needs to specify [JsonSerializerOptions.WriteIndented](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.writeindented?view=net-6.0) as an serialization parameter.
